apiVersion: batch/v1
kind: Job
metadata:
  name: dpt-benchmark
spec:
  template:
    spec:
      containers:
      - name: chris-dpt
        image: gitlab-registry.nrp-nautilus.io/christh9/dynamic-inference:latest
        command:
        - "python"
        args:
        - "/opt/repo/dynamic-inference/dpt_benchmark.py"
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: christh9-pvc
          mountPath: /christh9-pvc
        resources:
          limits:
            memory: 48Gi
            cpu: "6"
            nvidia.com/gpu: "1"
          requests:
            memory: 4Gi
            cpu: "1"
            nvidia.com/gpu: "1"    
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: user    
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: password    
        args:
          - clone
          - --single-branch
          - https://$(GIT_USERNAME):$(GIT_PASSWORD)@gitlab.nrp-nautilus.io/christh9/dynamic-inference
          - /opt/repo/dynamic-inference
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: christh9-pvc
        persistentVolumeClaim:
          claimName: christh9-pvc
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: gpu-type
                  operator: In
                  values:
                  - 1080Ti
  backoffLimit: 0