# multiple-gpu train
apiVersion: batch/v1
kind: Job
metadata:
  name: dpt-train2
spec:
  template:
    spec:
      containers:
      - name: chris-dpt2
        image: gitlab-registry.nrp-nautilus.io/christh9/dynamic-inference
        env:
        - name: CHASE_CI
          value: '1'
        command: ["stdbuf", "-i0", "-o0", "-e0", "/usr/bin/time", "-v", "bash", "-c"]
        args:
        - >-
          python3 
          /opt/repo/dynamic-inference/train_dpt.py
          -l 1e-4
          -b 16
          -e 200
          -k
        # command: ['sleep', '3650000000']
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: christh9-pvc
          mountPath: /christh9-pvc
        - name: dshm
          mountPath: /dev/shm
        resources:
          limits:
            memory: 128Gi
            cpu: "16"
            nvidia.com/gpu: "4"
          requests:
            memory: 96Gi
            cpu: "8"
            nvidia.com/gpu: "4"
      nodeSelector:
        nautilus.io/disktype: nvme
      initContainers:
      - name: init-clone-repo
        image: gitlab-registry.nrp-nautilus.io/christh9/dynamic-inference/setup
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: user    
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: password    
        command:
          - git
        args:
          - clone
          - --single-branch
          - --branch
          - intel-impl
          - --recurse-submodules
          - --remote-submodules
          - https://$(GIT_USERNAME):$(GIT_PASSWORD)@gitlab.nrp-nautilus.io/christh9/dynamic-inference
          - /opt/repo/dynamic-inference
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
          - name: ssh-key
            mountPath: /secrets
      volumes:
      - name: ssh-key
        secret:
          secretName: cho-ssh-key
          defaultMode: 0400
      - name: git-repo
        emptyDir: {}
      - name: christh9-pvc
        persistentVolumeClaim:
          claimName: christh9-pvc
      - name: dshm
        emptyDir:
          medium: Memory
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: gpu-type
                  operator: In
                  values:
                  - '3090'
                - key: topology.kubernetes.io/region
                  operator: In
                  values:
                  - us-west
  backoffLimit: 0