# for short ipynb sessions with good gpus
apiVersion: batch/v1
kind: Job
metadata:
  name: dpt-playground
spec:
  template:
    spec:
      containers:
      - name: chris-dpt
        image: gitlab-registry.nrp-nautilus.io/christh9/dynamic-inference
        command: ['sleep', '3650000000']
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: christh9-pvc
          mountPath: /christh9-pvc
        - name: dshm
          mountPath: /dev/shm
        resources:
          limits:
            memory: 32Gi
            cpu: "6"
            nvidia.com/gpu: "1"
          requests:
            memory: 16Gi
            cpu: "2"
            nvidia.com/gpu: "1"    
      initContainers:
      - name: init-clone-repo
        image: gitlab-registry.nrp-nautilus.io/christh9/dynamic-inference/setup
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: user    
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: password    
        command:
          - git
        args:
          - clone
          - --single-branch
          - --recurse-submodules
          - --remote-submodules
          - https://$(GIT_USERNAME):$(GIT_PASSWORD)@gitlab.nrp-nautilus.io/christh9/dynamic-inference
          - /opt/repo/dynamic-inference
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
          - name: ssh-key
            mountPath: /secrets
      volumes:
      - name: ssh-key
        secret:
          secretName: cho-ssh-key
          defaultMode: 0400
      - name: git-repo
        emptyDir: {}
      - name: christh9-pvc
        persistentVolumeClaim:
          claimName: christh9-pvc
      - name: dshm
        emptyDir:
          medium: Memory
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: gpu-type
                  operator: In
                  values:
                  - 'A40'
  backoffLimit: 0